# Generated by Django 5.1.6 on 2025-03-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahalla', '0004_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
